import "./globals.css";
import Navbar from "@/shared/Navbar/Navbar";
import Sidebar from "@/shared/Sidebar/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-center items-start h-screen w-screen bg-[#1d2125]">
          <Navbar />
          <div className="h-screen w-screen flex justify-center items-start">
            <Sidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
