import "./globals.css";
import ContextProvieder from "@/provider/ContextProvieder/ContextProvieder";
import Navbar from "@/shared/Navbar/Navbar";
import Sidebar from "@/shared/Sidebar/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        <ContextProvieder>
          <div className="flex flex-col justify-betweenl h-screen  bg-[#1d2125]">
            <Navbar />
            <div className="h-full w-full flex justify-center items-start">
              <Sidebar />
              {children}
            </div>
          </div>
        </ContextProvieder>

      </body>
    </html>
  );
}
